SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


IF EXISTS (SELECT 1
        FROM INFORMATION_SCHEMA.TABLES
        WHERE upper(TABLE_NAME) = 'SYSDOCUBRANDDETAILS' 
		AND upper(TABLE_SCHEMA) = 'EXT')
BEGIN
	DROP TABLE [ext].[SYSDOCUBRANDDETAILS]
END
GO


CREATE TABLE [ext].[SYSDOCUBRANDDETAILS](
		[ADDRESS] [nvarchar](250) NOT NULL,
		[ADDRESSCOLLAPSE] [int] NOT NULL,
		[ADDRESSDELIMITER] [nvarchar](5) NOT NULL,
		[BRANDID] [nvarchar](30) NOT NULL,
		[BRANDNAME] [nvarchar](60) NOT NULL,
		[EMAIL] [nvarchar](80) NOT NULL,
		[IMAGE1] [varbinary](max) NULL,
		[IMAGE1NAME] [nvarchar](60) NOT NULL,
		[IMAGE2] [varbinary](max) NULL,
		[IMAGE2NAME] [nvarchar](60) NOT NULL,
		[IMAGE3] [varbinary](max) NULL,
		[IMAGE3NAME] [nvarchar](60) NOT NULL,
		[LOGISTICSLOCATIONRECID] [bigint] NOT NULL,
		[NOTESLINE1] [nvarchar](254) NOT NULL,
		[NOTESLINE2] [nvarchar](254) NOT NULL,
		[NOTESLINE3] [nvarchar](254) NOT NULL,
		[PHONE] [nvarchar](20) NOT NULL,
		[PHONELOCAL] [nvarchar](10) NOT NULL,
		[PRIMARYCOLOR] [nvarchar](30) NOT NULL,
		[SECONDARYCOLOR] [nvarchar](30) NOT NULL,
		[REPORTNAME] [nvarchar](40) NOT NULL,
		[DESIGNNAME] [nvarchar](40) NOT NULL,
		[TELEFAX] [nvarchar](20) NOT NULL,
		[URL] [nvarchar](255) NOT NULL,
		[RECID] [bigint] NOT NULL,
	 CONSTRAINT [PK_SYSDOCUBRANDDETAILS] PRIMARY KEY CLUSTERED 
	(
		[RECID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[SYSDOCUBRANDDETAILS] TO [UsersRole]
	GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[SYSDOCUBRANDDETAILS] TO [DeployExtensibilityRole]
	GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[SYSDOCUBRANDDETAILS] TO [DataSyncUsersRole]

GO


IF NOT EXISTS (SELECT 1
        FROM INFORMATION_SCHEMA.TABLES
        WHERE upper(TABLE_NAME) = 'SYSDOCUBRANDIMAGES' 
		AND upper(TABLE_SCHEMA) = 'EXT')
BEGIN

	CREATE TABLE [ext].[SYSDOCUBRANDIMAGES](
		[DESCRIPTION] [nvarchar](60) NOT NULL,
		[FORMAT] [nvarchar](10) NOT NULL,
		[IMAGE] [varbinary](max) NULL,
		[NAME] [nvarchar](60) NOT NULL,
		[RECID] [bigint] NOT NULL,
	 CONSTRAINT [PK_SYSDOCUBRANDIMAGES] PRIMARY KEY CLUSTERED 
	(
		[RECID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[SYSDOCUBRANDIMAGES] TO [UsersRole]
	GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[SYSDOCUBRANDIMAGES] TO [DeployExtensibilityRole]
	GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[SYSDOCUBRANDIMAGES] TO [DataSyncUsersRole]

END
GO

------------------------------------------------------------

IF EXISTS (SELECT 1
        FROM INFORMATION_SCHEMA.TABLES
        WHERE upper(TABLE_NAME) = 'AxxRETAILSTORETABLERPTIMAGES' 
		AND upper(TABLE_SCHEMA) = 'EXT')
BEGIN
	DROP TABLE [ext].[AxxRetailStoreTableRptImages];
END

CREATE TABLE [ext].[AxxRetailStoreTableRptImages] (
	[AxxINVOICEIMAGES] [nvarchar](30) NOT NULL DEFAULT '',
	[AxxQUOTEIMAGES] [nvarchar](30) NOT NULL DEFAULT '',
	[RECID] [bigint] NOT NULL DEFAULT 0,
	[STORENUMBER] [nvarchar](10) NOT NULL DEFAULT '',
 CONSTRAINT [PK_AxxRetailStoreTableRptImages] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
	
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[AxxRetailStoreTableRptImages] TO [UsersRole]
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[AxxRetailStoreTableRptImages] TO [DeployExtensibilityRole]
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[AxxRetailStoreTableRptImages] TO [DataSyncUsersRole]

GO


IF NOT EXISTS (SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE upper(TABLE_NAME) = 'AxxRETAILSTORETABLERPTIMAGES'
		AND upper(TABLE_SCHEMA) = 'EXT'
        AND upper(COLUMN_NAME) = 'AxxINVOICEIMAGES')
BEGIN
	 ALTER TABLE [ext].[AxxRetailStoreTableRptImages] ADD 
		[AxxINVOICEIMAGES] [nvarchar](30) NOT NULL DEFAULT '',
		[AxxQUOTEIMAGES] [nvarchar](30) NOT NULL DEFAULT ''
END
GO


IF EXISTS (SELECT 1
	FROM INFORMATION_SCHEMA.ROUTINES
    WHERE upper(ROUTINE_NAME) = 'AxxGETDOCUBRANDIMAGES' 
	AND upper(ROUTINE_SCHEMA) = 'EXT')
BEGIN
	DROP PROCEDURE [ext].[AxxGETDOCUBRANDIMAGES];
END
GO

CREATE PROCEDURE [ext].[AxxGETDOCUBRANDIMAGES]
	@tvp_QueryResultSettings	[crt].[QUERYRESULTSETTINGSTABLETYPE] READONLY,
	@BrandId					[nvarchar](30) = '',
	@ImageNumber				[int] = 0
AS
BEGIN
    SET NOCOUNT ON

	DECLARE @ImageName [nvarchar](60);

	IF (@ImageNumber = 1)
	BEGIN
		SELECT @ImageName = d.IMAGE1NAME FROM [ext].[SYSDOCUBRANDDETAILS] d 
			WHERE d.BRANDID = @BrandId;
	END;

	IF (@ImageNumber = 2)
	BEGIN
		SELECT @ImageName = d.IMAGE2NAME FROM [ext].[SYSDOCUBRANDDETAILS] d 
			WHERE d.BRANDID = @BrandId;
	END;

	IF (@ImageNumber = 3)
	BEGIN
		SELECT @ImageName = d.IMAGE3NAME FROM [ext].[SYSDOCUBRANDDETAILS] d 
			WHERE d.BRANDID = @BrandId;
	END;

	SELECT i.DESCRIPTION, i.FORMAT, i.NAME, i.IMAGE, i.RECID FROM [EXT].[SYSDOCUBRANDIMAGES] i WHERE i.NAME = @ImageName;

END;

GO
