IF (SELECT OBJECT_ID('[ext].[TRNLGRETAILFUNCTIONALITYPROFILE]')) IS NOT NULL
BEGIN
    DROP TABLE [ext].[TRNLGRETAILFUNCTIONALITYPROFILE]
END

CREATE TABLE [ext].[TRNLGRETAILFUNCTIONALITYPROFILE] (
    [RECID] [bigint] NOT NULL,
    [PROFILEID] [NVARCHAR](10) NOT NULL,
    [TRNLGISQUOTATION] [INT] NOT NULL,  
    CONSTRAINT [I_TRNLGRETAILFUNCTIONALITYPROFILE_RECID] PRIMARY KEY CLUSTERED ([RECID] ASC) WITH (
        PAD_INDEX = OFF
        ,STATISTICS_NORECOMPUTE = OFF
        ,IGNORE_DUP_KEY = OFF
        ,ALLOW_ROW_LOCKS = ON
        ,ALLOW_PAGE_LOCKS = ON
        ) ON [PRIMARY]
    ) ON [PRIMARY]

--ALTER TABLE [ext].[TRNLGRETAILFUNCTIONALITYPROFILE]
--    WITH CHECK ADD CHECK (([RECID] <> (0)))

GO
GRANT SELECT,INSERT,UPDATE,DELETE ON OBJECT::[ext].[TRNLGRETAILFUNCTIONALITYPROFILE] TO [UsersRole]
GRANT SELECT,INSERT,UPDATE,DELETE ON OBJECT::[ext].[TRNLGRETAILFUNCTIONALITYPROFILE] TO [DeployExtensibilityRole]
GRANT SELECT,INSERT,UPDATE,DELETE ON OBJECT::[ext].[TRNLGRETAILFUNCTIONALITYPROFILE] TO [DataSyncUsersRole]
GO