<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ProcessReport\GenerateReportGeneric.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataModel\DataModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ProcessReport\ReportModel\AxxCustomerOrder.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ProcessReport\ReportModel\QuotationReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ProcessReport\PrintReports\" />
  </ItemGroup>

</Project>
